[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gco"
version = "0.1.0"
description = "Grassmannian Covering Optimizer"
requires-python = ">=3.9"
authors = [
    { name = "Ton Nom", email = "ton.email@exemple.com" }
]
dependencies = [
    "numpy",
    "PyNomadBBO", 
    "scikit-learn",
    "pymanopt"
]

[project.urls]
Repository = "https://github.com/tonpseudo/GrassmannianCoveringOptimizer"

[tool.setuptools.packages.find]
where = ["."]
include = ["GCO*"]